sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install:	
  - ./gradlew org.inaetics.wiring:build

script: true

after_success:
  - git clone https://github.com/bpetri/deployment_test.git $TRAVIS_BUILD_DIR/deployment_test && cd $TRAVIS_BUILD_DIR/deployment_test
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - cp $TRAVIS_BUILD_DIT/org.inaetics.wiring/generated/*.jar $TRAVIS_BUILD_DIR/deployment_test 
  - git add *.jar && git commit -m "build" && git push -f 

