sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install:	
  - ./gradlew org.inaetics.wiring:build

deploy:
  provider: bintray
  file: $TRAVIS_BUILD_DIR/deployment.json
  user: bpetri
  key: $BINTRAY_KEY
